lib/wave_web/router.ex
defmodule WaveWeb.Router do
  use WaveWeb, :router
  import Plug.BasicAuth
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WaveWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug :auth
  end

  pipeline :traced do
    plug WaveWeb.Plugs.Trace
  end

  scope "/", WaveWeb do
    pipe_through :browser

    get "/tracing", ContactController, :index
    post "/tracing", ContactController, :create
  end

  scope "/dashboard", WaveWeb do
    pipe_through [:browser, :protected]

    live "/", DashboardLive
    live "/settings", DashboardSettingsLive
    live "/tracing", DashboardTracingLive
    live_dashboard "/app", metrics: WaveWeb.Telemetry, ecto_repos: [Wave.Repo]
  end

  scope "/", WaveWeb do
    pipe_through [:browser]

    live "/", PageLive, :index
    live "/table/:table_id", WaveLive
  end

  defp auth(conn, opts) do
    password = Application.fetch_env!(:wave, :dashboard_password)
    Plug.BasicAuth.basic_auth(conn, username: "admin", password: password)
  end
end

lib/wave/tracing/contact.ex
defmodule Wave.Tracing.Contact do
  use Ecto.Schema
  import Ecto.Changeset

  schema "contacts" do
    field :city, :string
    field :firstname, :string
    field :lastname, :string
    field :phone, :string

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(contact, attrs) do
    contact
    |> cast(attrs, [:lastname, :firstname, :city, :phone])
    |> validate_required([:lastname, :firstname, :city, :phone])
  end
end

lib/wave_web/controllers/contact_controller.ex
defmodule WaveWeb.ContactController do
  use WaveWeb, :controller
  alias Wave.Tracing
  alias Wave.Tracing.Contact
  alias Wave.Pubsub

  def index(conn, _params) do
    conn
    |> assign(:changeset, Tracing.change_contact(%Contact{}))
    |> render("index.html")
  end

  def create(conn, %{"contact" => contact_params}) do
    case Tracing.create_contact(contact_params) do
      {:ok, _contact} ->
        Pubsub.broadcast(:trace)

        conn
        |> put_flash(:info, "You are now T R A C E D 👁")
        |> put_session(:traced, true)
        |> redirect(to: "/")

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "index.html", changeset: changeset)
    end
  end
end

lib/wave_web/views/contact_view.ex
defmodule WaveWeb.ContactView do
  use WaveWeb, :view
end

lib/wave_web/templates/contact/index.html.eex
<div class="flex flex-col max-w-lg px-4 mx-auto text-xl text-center" >
<div class="my-10 text-3xl font-bold">Contact Tracing</div>

<%= form_for @changeset, Routes.contact_path(@conn, :create),
  fn f -> %>

  <div>
  <%= label f, :firstname, class: "block text-left" %>
  <%= text_input f, :firstname, class: "block text-black rounded-lg w-full px-1" %>
  </div>
  <div class="mb-2">
  <%= error_tag f, :firstname %>
  </div>

  <div>
  <%= label f, :lastname, class: "block text-left" %>
  <%= text_input f, :lastname, class: "block text-black rounded-lg w-full px-1" %>
  </div>
  <div class="mb-2">
  <%= error_tag f, :lastname %>
  </div>

  <div>
  <%= label f, :city, class: "block text-left" %>
  <%= text_input f, :city, class: "block text-black rounded-lg w-full px-1" %>
  </div>
  <div class="mb-2">
  <%= error_tag f, :city %>
  </div>

  <div>
  <%= label f, :phone, class: "block text-left" %>
  <%= text_input f, :phone, class: "block text-black rounded-lg w-full px-1" %>
  </div>
  <div class="mb-2">
  <%= error_tag f, :phone %>
  </div>

  <%= submit "Submit", phx_disable_with: "Submitting...", class: "disabled:bg-wave-gray py-3 bg-wave-blue text-white rounded-full mt-5 w-full" %>
<% end %>
</div>